const CODE_OF_MONTHS = [null, 1, 4, 4, 0, 2, 5, 0, 3, 6, 1, 4, 6];
const NUMBER_DAYS_OF_WEEK = 7;
const MIN_YEAR_LENGHT = 3;
const NUMBER_OF_DIGIT = 10;
const NUM_DAYS_OF_BIG_MONTHS = 31;
const NUM_DAYS_OF_SMALL_MONTHS = 30;
const NUM_DAYS_OF_BIG_FEBRUARY = 29;
const NUM_DAYS_OF_SMALL_FEBRUARY = 28;
const NUM_CALENDAR_CELLS = 42;
const INDEX_CHECK_LEAP_YEAR = 4;
const INDEX_CHECK_LEAP_YEAR_2 = 100;
const INDEX_CHECK_LEAP_YEAR_3 = 400;
const STRING_FIRST_NUMBER = '01';

module.exports = {
  CODE_OF_MONTHS,
  NUMBER_DAYS_OF_WEEK,
  MIN_YEAR_LENGHT,
  NUMBER_OF_DIGIT,
  NUM_DAYS_OF_BIG_MONTHS,
  NUM_DAYS_OF_SMALL_MONTHS,
  NUM_DAYS_OF_BIG_FEBRUARY,
  NUM_DAYS_OF_SMALL_FEBRUARY,
  NUM_CALENDAR_CELLS,
  INDEX_CHECK_LEAP_YEAR,
  INDEX_CHECK_LEAP_YEAR_2,
  INDEX_CHECK_LEAP_YEAR_3,
  STRING_FIRST_NUMBER
};
